<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models;

use stdClass;

class MarkMessageAsReadRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $messagingProduct;

    /**
     * @var string
     */
    private $status;

    /**
     * @var string
     */
    private $messageId;

    /**
     * @param string $messagingProduct
     * @param string $status
     * @param string $messageId
     */
    public function __construct(string $messagingProduct, string $status, string $messageId)
    {
        $this->messagingProduct = $messagingProduct;
        $this->status = $status;
        $this->messageId = $messageId;
    }

    /**
     * Returns Messaging Product.
     * Messaging service used for the request. Use 'whatsapp'.
     */
    public function getMessagingProduct(): string
    {
        return $this->messagingProduct;
    }

    /**
     * Sets Messaging Product.
     * Messaging service used for the request. Use 'whatsapp'.
     *
     * @required
     * @maps messaging_product
     */
    public function setMessagingProduct(string $messagingProduct): void
    {
        $this->messagingProduct = $messagingProduct;
    }

    /**
     * Returns Status.
     * A message's status. You can use this field to mark a message as read.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * A message's status. You can use this field to mark a message as read.
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Message Id.
     * Id of the incoming message.
     */
    public function getMessageId(): string
    {
        return $this->messageId;
    }

    /**
     * Sets Message Id.
     * Id of the incoming message.
     *
     * @required
     * @maps message_id
     */
    public function setMessageId(string $messageId): void
    {
        $this->messageId = $messageId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['messaging_product'] = $this->messagingProduct;
        $json['status']            = $this->status;
        $json['message_id']        = $this->messageId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
